### ISSUE TITLE
As a developer I want better theming support in Tutor

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#11]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

- Sofiane has started work on two related items, they are in progress now.
- Would allow the installaton of brand assets withing docker images for MFEs.  Discussion is here: https://discuss.overhang.io/t/customise-mfes-branding/2029

From the Tutor OEP:

There should be a way to reuse the same base LMS image with different themes without having to bake them into the image

Note: there are different ways to address this. I suspect that there will be different solutions for the docker-compose and the Kubernetes deployments.

**Comment by regisb** [comment]
> There should be a way to reuse the same base LMS image with different themes without having to bake them into the image

I'm not so sure about that one. The whole idea of Docker is that everything should ship as a single image. The only way I see this could work were if we stored static assets in object storage, such as S3/MinIO. With this approach, we could re-generate static assets from a different host, and changes would be visible live in production. But we would not be able to publish changes made to html files, and I suspect this would be a major issue for most people.

This is typically the type of issue that other contributors should work on, because I have no idea what is the actual problem that we need to solve.

**Comment by kdmccormick** [comment]
Yeah, I'm not familiar with the problem either. I copied it from the google sheet, which I think drew it from the [wishlist in the Tutor OEP ADR](https://github.com/openedx/open-edx-proposals/blob/master/oeps/architectural-decisions/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst#wishlist). There's some [discussion on the ADR's PR](https://github.com/openedx/open-edx-proposals/pull/178#discussion_r543168417) as well.

@e0d or @arbrandes - Do you know what problem is being identified here and whether it's something we should have in our backlog for Tutor?

**Comment by arbrandes** [comment]
@kdmccormick, this is an idea I captured while thinking up ways to reduce the necessity of rebuilding Tutor images.  And as @regisb points out, yes, I was thinking in terms of using object storage to retrieve assets/artifacts at runtime.

But I clearly did not think it through, as indeed HTML would be an intractable problem for anything rendered Django-side.  So if this is the primary purpose of this ticket, then we can drop it.  (The idea might still be valid for SPAs like our MFEs, but there are probably better places to track this than here.)

**Comment by kdmccormick** [comment]
Thanks for the details @arbrandes .

> HTML would be an intractable problem for anything rendered Django-side. So if this is the primary purpose of this ticket, then we can drop it. (The idea might still be valid for SPAs like our MFEs, but there are probably better places to track this than here.)

Agreed 👍🏻
