### ISSUE TITLE
As a deployer I want to be able to migrate from the "native release" to Tutor easily

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#12]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

If Tutor is to become the official binary distribution for Open edX we should have a recipe for migrating folks on a native release to Tutor

Some preliminary work already exists, but further work is required to make the process smoother and more robust.

**Comment by regisb** [comment]
This issue is tracked here by the BTR working group: https://github.com/openedx/build-test-release-wg/issues/78
Unfortunately I don't have more info about this issue than what is already mentioned there, because I have not run the native installation for many years.

**Comment by kdmccormick** [comment]
Closing this in favor of the BTR issue.
