### ISSUE TITLE
Replace the `quickstart` gifs with new `launch` gifs

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/wg-developer-experience#120]
see https://github.com/overhangio/tutor/pull/724#issuecomment-1252902228

**Comment by regisb** [comment]
This can wait until Olive.

**Comment by kdmccormick** [comment]
Added this to the 2022-12-07 epic so that we remember to do it pre-Olive.

**Comment by kdmccormick** [comment]
Done here: https://github.com/overhangio/tutor/commit/c26999ec658a216b68797e2d38c522ff53e7fbd3#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR59-R61

Result: https://docs.tutor.overhang.io/index.html#features
