### ISSUE TITLE
As a deployer I want to be able to run integration tests in Tutor

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#14]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

There should be a well documented recipe for running integration tests in Tutor.

A team at edX has been evaluating our testing frameworks on the python side and we are converging on cypress for end-to-end tests from a user perspective, and PACT for contract-based testing in python between dependent services.

Note: I suspect we will have to jump through many hoops to run integration tests in edx-platform. Further work will be necessary to run integration tests in other IDAs.

**Comment by regisb** [comment]
Ed suggested that we get rid of bok-choy before we attempt to tackle this one. The deprecation process [has been launched](https://discuss.openedx.org/t/deprecation-removal-bok-choy-test-suites-framework/6547) (thanks @kdmccormick :)). Given that no direct replacement has been suggested yet ([source](https://openedx.atlassian.net/browse/DEPR-174)) I believe that we can close this issue for now -- and focus on #4 instead.

**Comment by kdmccormick** [comment]
+1

**Comment by kdmccormick** [comment]
Somewhat related: https://github.com/openedx/wg-developer-experience/issues/164
