### ISSUE TITLE
Fix tests that pass in Devstack but do not pass in Tutor Nightly 

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/wg-developer-experience#155]
### Background

This came from a re-do of #110 due to [a variety of reasons](https://github.com/openedx/wg-developer-experience/issues/36#issuecomment-1352120539).

Detailed results of running pytests for cms, lms, openedx, common, and xmodule can be found in this [new spreadsheet](https://docs.google.com/spreadsheets/d/1iu-Z3J_P_1m2pGIoTXAqx0YnQ5cJx6k85VnMpRSGvag/edit#gid=778843154).

### Output

- https://github.com/openedx/wg-developer-experience/issues/156

### Notes

In addition to the 1 test that is skipped in Tutor but passes in Devstack, there are 12 tests that Fail as well as 399 tests that are skipped in both Devstack and Tutor.

**Comment by kdmccormick** [comment]
Since there's only one test to fix right now, I'm closing this in favor of https://github.com/openedx/wg-developer-experience/issues/156 and https://github.com/openedx/wg-developer-experience/issues/157.
