### ISSUE TITLE
Run `TestSafeOrNot:test_cant_do_something_forbidden` in Tutor

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#156]
### Background

In https://github.com/openedx/wg-developer-experience/issues/155 we cataloged whether each edx-platform test fails, passes, or is skipped in both Devstack and Tutor Nightly (using edx-platform master, in Jan 2023).

This one test passes in Devstack but is skipped in Tutor: `edx-platform:xmodule/capa/safe_exec/tests/test_safe_exec.py::TestSafeOrNot::test_cant_do_something_forbidden`

### Tasks

Fix the test or Tutor so that running:
```
tutor dev run lms bash
  lms> unset DJANGO_SETTINGS_MODULE
  lms> unset SERVICE_VARIANT
  lms> export EDXAPP_TEST_MONGO_HOST=mongodb
  lms> pytest 'xmodule/capa/safe_exec/tests/test_safe_exec.py::TestSafeOrNot::test_cant_do_something_forbidden'
```
in Tutor Nightly passes.

(test running instructions came from here: https://docs.tutor.overhang.io/dev.html#running-edx-platform-unit-tests)

### Notes

safe_exec calls out to Codejail. So, this is likely the result of some Codejail configuration, or related environment setup, that Devstack has but Tutor does not.

The test can ran in Devstack with:
```
make lms-shell
  lms> pytest 'xmodule/capa/safe_exec/tests/test_safe_exec.py::TestSafeOrNot::test_cant_do_something_forbidden'
```

**Comment by solababs** [comment]
@kdmccormick I am working on this issue and here is what i have found
From the security issue mentioned here https://github.com/overhangio/tutor/pull/443 we see that the python interpreter is explicitely disabled.
How do we want to go about this now?
cc @xitij2000

**Comment by xitij2000** [comment]
@solababs Looking into this issue I see that you can use the plugin [tutor-contrib-codejail](https://github.com/eduNEXT/tutor-contrib-codejail/) plugin to enable codejail. 

Does enabling that plugin allow the test to run? Does it pass? If so, I personally feel this issue can be closed since the test can pass on tutor.

**Comment by solababs** [comment]
@xitij2000 Thanks for your help on this. I have been able to adequately implement tutor-contrib-codejail and the the test passed on tutor.
Please let me know what to do with this ticket.

**Comment by xitij2000** [comment]
> @xitij2000 Thanks for your help on this. I have been able to adequately implement tutor-contrib-codejail and the the test passed on tutor. Please let me know what to do with this ticket.

Can you create a PR againt edx-platform that changes the condition in which the test is considered skipped? The test should run if tutor is configured with the codejail service.

**Comment by solababs** [comment]
@xitij2000 please see linked PR https://github.com/openedx/edx-platform/pull/32955
