### ISSUE TITLE
As a deployer I need a clearly documented path forward to deploy Open edX at scale

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#16]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

Tutor currently supports running at scale on Kubernetes, but we should document more precisely the necessary steps. This will create more confidence in Open edX as a product.

Note: this is not really a technical problem, but more of a documentation and communication effort.

**Comment by regisb** [comment]
There is now an awesome tutorial for that! https://docs.tutor.overhang.io/tutorials/scale.html

**Comment by kdmccormick** [comment]
🔥
