### ISSUE TITLE
As a developer I want to be able to develop MFEs within tutor

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#17]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

- Basis working version is in review now 2021-11-02

MFE should be supported and easily addable.  Hot reloading of MFE code must work.

Note: this is already (mostly) the case. Hot reloading would need some polishing.

**Comment by regisb** [comment]
Hot reloading now works out of the box. I'm not sure what needs to be done here on the Tutor-side. There is still some work to do in MFEs themselves, though; on that topic see this conversation that I started https://discuss.openedx.org/t/microfrontends-a-retrospective/6486

**Comment by kdmccormick** [comment]
👍🏻
