### ISSUE TITLE
As a developer I want to track arbitrary branches

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#18]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

This is possible, but not easy:
- Need docs, at least
- A plugin that checks outs branches could be a possibility.
- Hot reloading already works.

Tutor works seamlessly with arbitrary branches of Open edX repositories including main/master

Note: this is already possible, but the difficulty resides in tracking upstream changes from the master branch.

**Comment by regisb** [comment]
All technical features are in place to close this issue. Running up-to-date master branches is documented here: https://docs.tutor.overhang.io/tutorials/nightly.html
I believe that the only thing that might be missing is a good step-by-step tutorial on how to run a fork of edx-platform, or some other IDA.

**Comment by kdmccormick** [comment]
Closing this so that we can consolidate discussion into https://github.com/overhangio/2u-tutor-adoption/issues/43
