### ISSUE TITLE
As a developer I want access to more IDAs

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#2]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

- edX MFEs have not been added.
- FUN Richie was added as a catalog/marketing site option
- [ ] Ed to make sure we have the list of IDAs that are needed.
https://openedx.atlassian.net/wiki/spaces/AC/pages/2451276919/Tutor+Analysis

Tutor should have a well documented recipe for adding additional services as plugins.  This road should be well paved, though the work can be done by folks outside the Tutor core team.

Questions:

+ Is there a registry from plugins
+ What's the best way to support multiple topologies?  Extended templates?

Note: obviously, the complexity of adding extra IDAs will depend on how complex they are. E.g: the ecommerce IDA takes more effort than others.

**Comment by regisb** [comment]
> edX MFEs have not been added.

This is now done as part of the tutor-mfe plugin: https://github.com/overhangio/tutor-mfe

> FUN Richie was added as a catalog/marketing site option

A plugin now exists, thanks to support from FUN (cc @sampaccoud): https://github.com/overhangio/tutor-richie

> Is there a registry from plugins

Currently, the only list of officially supported plugins is from the overhang.io website: https://overhang.io/tutor/plugins
This list is linked to from here: https://docs.tutor.overhang.io/plugins.html#existing-plugins

We should definitely provide a publicly-editable list of plugins. I suggest to add a table to the Tutor documentation listing all plugins. The table must include the following information:

- Name
- Short description
- Supported releases/tutor versions
- Link to project page, which must include the following information:
    - Setup instructions
    - How to get support

When a plugin does not support the latest release, it will be moved to an "older plugins" table.

**Comment by kdmccormick** [comment]
Closing this issue in favor of:
* https://github.com/overhangio/2u-tutor-adoption/issues/46
* https://github.com/overhangio/2u-tutor-adoption/issues/42 (I can work with the WG at 2U will find out which IDAs they are missing and how they'll get plugins built for them)
