### ISSUE TITLE
As a user of Tutor, I want support getting started and solving problems

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#20]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

**Comment by regisb** [comment]
I'm not sure what this entry covers. Should we improve the "what next" documentation page? https://docs.tutor.overhang.io/whatnext.html

**Comment by kdmccormick** [comment]
Looking back to the spreasheet where I got this story, I forgot to copy in this paragraph:

> Provide consistent support in the the forums -- Slack and Discourse -- for users of Tutor to ensure that problems are addressed in a timely fashion.  Monitor and respond to Github issues.


Sounds like more of a community/business arrangement than a story. Do you see any value in having this issue open on our backlog @regisb ?

**Comment by regisb** [comment]
I agree. No, I think we can close this one.
