### ISSUE TITLE
Make sure that a plugin can be made for auto-generating test data

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#3]
## Context

2U devs will want to be able to automatically populate their Tutor dev instance with test data sets in order to manually test some of the more complex features of the platform.

This should be doable via the plugin system.

## Acceptance

Ensure that Plugin API v1 is suitable for making a plugin that generates test data into any service.

**Comment by regisb** [comment]
Do we really want to generate test data automatically? If yes, what data? Unless I'm mistaken, it should be really simple to generate such data with a plugin.

**Comment by kdmccormick** [comment]
When I think of "test data sets", I think of sizeable sets of fake-but-reasonable data that developers can use to manually test that their features work as expected when given nontrivial data.

Example: To fully test the learner dashboard, one might need a non-staff user who is enrolled in several different courses, each in a different course mode, with some courses complete and others incomplete, and some courses part of a program and others standalone. It would take a several management command invocations to get there.

It is important that Tutor provides a mechanism for loading in test data sets, but it would be wrong for Tutor itself to include said data. I believe the Plugin system is well-suited for this job.  I could imagine a workflow looking like:
```
# install and enable a plugin for LMS test data
pip install tutor-contrib-testdata-lms
tutor plugins enable testdata-lms

# run management commands and/or direct database queries needed in order to
# provision a set of testing data "myuser"
tutor testdata-lms provision-learner-for-dashboard --username=myuser
```
Ideally these plugins would be maintained by the teams that depend on them.

**Comment by kdmccormick** [comment]
I've updated the acceptance criteria to reflect that we expect this to be a no-op, assuming the plugin API exposes some interface for running shell commands in containers.

**Comment by kdmccormick** [comment]
Blocked by #75

**Comment by kdmccormick** [comment]
Actually, the Acceptance Criteria is just to "make it possible to auto-generate data". Since #75 would fulfill that, I'm closing this as a duplicate.
