### ISSUE TITLE
Catalog edx-platform tests that fail, both for Tutor and for Devstack

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#36]
## Context

There are some tests that don't work in Tutor. There are also some tests that don't work in Devstack. For the rollout of Tutor to 2U developers, it would be reasonable to ensure that the tests that pass in Devstack also pass in Tutor.

To achieve this, we need to catalog which tests currently don't work. In this issue, we focus on edx-platform tests. A future issue will capture tests for IDAs and MFEs.

## Acceptance

* Run all edx-platform test suites (python unit, js unit, python quality, js quality) within both Devstack and Tutor on master.
* Catalog the tests or suites that fail.
* Make new issue(s) to fix tests that fail in Tutor but pass in Devstack.

## Results

Sheet: https://docs.google.com/spreadsheets/d/1CHiFOh2RpPlljNNF5rltEgOLGpKe1W35oy5Qms0-JXo/edit#gid=0

Issue list: https://github.com/overhangio/2u-tutor-adoption/issues/110

**Comment by regisb** [comment]
For the record, here are the instructions on how to run tests in Tutor: https://docs.tutor.overhang.io/dev.html#running-edx-platform-unit-tests

It's really too bad that we have to define these environment variables manually to be able to run the test suite. I wish that we could simply run `pytest` to run all the unit tests.

**Comment by kdmccormick** [comment]
Strongly agree @regisb . If possible I think that is something we should fix in edx-platform itself--no sense in complicating Tutor or its docs to work around something that is clearly wrong upstream.

**Comment by kdmccormick** [comment]
@regisb Based on your comment I split out a separate ticket: https://github.com/overhangio/2u-tutor-adoption/issues/48

**Comment by Carlos-Muniz** [comment]
I'm tackling this issue. Feel free to assign it to me!
I'll be running the tests via Tutor's nightly branch.

**Comment by Carlos-Muniz** [comment]
Here is [the complete list of pytests and their results ran in Devstack and Tutor](https://docs.google.com/spreadsheets/d/1CHiFOh2RpPlljNNF5rltEgOLGpKe1W35oy5Qms0-JXo/edit?usp=sharing).

**Comment by Carlos-Muniz** [comment]
New issues have been made for tests that pass in Devstack but do not pass in Tutor.

**Comment by kdmccormick** [comment]
Thanks @Carlos-Muniz !

**Comment by kdmccormick** [comment]
@Carlos-Muniz I hate to do this to you, but I just realized we missed the tests in the `xmodule` top-level directory. The `xmodule` directory is new on the edx-platform master branch. Although [we've updated the Tutor Nightly docs with the new instructions](https://github.com/overhangio/tutor/pull/703), the directions you read on docs.tutor.overhang.io are based on Tutor's master branch.

**Comment by Carlos-Muniz** [comment]
@kdmccormick Completed the xmodule pytests for Tutor and Devstack and recorded it in the spreadsheet, and made new issues for each of the pytest classes.

**Comment by kdmccormick** [comment]
All issues for fixing tests are collected here: https://github.com/overhangio/2u-tutor-adoption/issues/110

**Comment by kdmccormick** [comment]
Since @Carlos-Muniz last ran these, looks like the set of failing tests has changed. Furthermore, we've realized that the test randomization behavior causes ddt tests to be renamed (based on their order) which caused issues when comparing tests [in the spreadsheet](https://docs.google.com/spreadsheets/d/1CHiFOh2RpPlljNNF5rltEgOLGpKe1W35oy5Qms0-JXo/edit#gid=0). Carlos will be re-running and cataloging the tests.

**Comment by Carlos-Muniz** [comment]
@kdmccormick A new issue #155 has been created for the latest running of pytests in Devstack and Tutor. Issue #110, and related issues can also be closed.

**Comment by kdmccormick** [comment]
Cataloged here, in a new sheet: https://docs.google.com/spreadsheets/d/1iu-Z3J_P_1m2pGIoTXAqx0YnQ5cJx6k85VnMpRSGvag/edit#gid=778843154
