### ISSUE TITLE
Why are official plugins installed differently than entrypoint plugins?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#37]
## Context

There are three types of plugins:

1. `DictPlugins`: simple YAML files placed at plugin root.
2. `EntrypointPlugins`: Python projects; when installed, they expose plugin(s) via the `tutor.plugin.v0` setup.py entrypoint.
3. `OfficialPlugins`:  Python projects; Tutor loads a hard-coded list of them in `main.py`. 

Why is the `OfficialPlugin` path necessary? Could Tutor instead just treat the official plugins like any other `EntrypointPlugin`, using a hard-coded list of plugins to enable by default?

Potential benefits:
* tutor repo users (eg nightly users) get the same plugin experience as `pip install tutor` users
* plugin loader implementation simplicity

## Acceptance

See @regisb's comment bellow explaining why `OfficialPlugin` is used. See whether `EntrypointPlugin` could be used at the build step reliably instead.
* If so: Replace `OfficialPlugin` usage at the build step with `EntrypointPlugin` usage.
* If not: Add a note to the `OfficialPlugin` and/or`tutor/main.py` docstrings explaining their necessity.

**Comment by regisb** [comment]
A couple assumptions are made about `OfficialPlugin` instances:

1. The plugin import path is `tutor{plugin_name}.plugin`.
1. Their version number is defined as `tutor{plugin_name}.__about.__version__`.

Not all Python plugins generated by the plugin cookiecutter would follow this pattern, so we should not make these assumptions for all plugins.

These assumptions allow us to load these plugins explicitly with `OfficialPlugin.load` when building the binary bundle with `pyinstaller`. I forget why I didn't go with `EntrypointPlugin`, but I believe it has to do with the fact that we cannot reliably iterate on entrypoints during the build step.

**Comment by kdmccormick** [comment]
This doesn't seem important.
