### ISSUE TITLE
As a developer, I want to load catalog data from the Discovery service

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#38]
## Context

The Discovery service holds catalog data, such as the relationship between course runs, courses, and programs. LMS has this god-awful setup where an automation server regularly calls the Discovery API to get the entire catalog and stuffs the results into memcached, allowing LMS to quickly access the catalog data.

Devstack lets you simulate this: https://github.com/openedx/devstack/tree/master/programs

We will need a Tutor plugin that'll also allow you to simulate this easily. `tutor-discovery` is probably that plugin. It's possible that `tutor-discovery` already supports this... need to confirm.

## AC

TBD

**Comment by regisb** [comment]
> LMS has this god-awful setup where an automation server regularly calls the Discovery API to get the entire catalog and stuffs the results into memcached, allowing LMS to quickly access the catalog data.

Call me lazy, but isn't the "right" solution actually to improve the integration of the discovery catalog with the LMS? Full disclaimer: I have no idea what's this catalog data.

**Comment by kdmccormick** [comment]
@regisb yes, that is the Right solution. I sure hope somebody does it one day.

In the meantime, it looks like the official discovery plugin already handles this: https://github.com/overhangio/tutor-discovery#caching-programs
