### ISSUE TITLE
Tracking logs not working?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#64]
## Context

Potential bug report from @e0d:

> Do tracking logs typically work automatically in the dev environment?
> * Containers are demonized
> * Log file was created, but remains empty, 0 May 18 22:35 tracking.log, after activity.
>
> ...
>
> I'd expect this file to not be empty: `ls -lrt $(tutor config printroot)/data/lms/logs/tracking.log`

Running using `tutor local` on stable branch

## Subtasks

* Figure out why tracking log aren't working
* Determine if a bug fix and/or docs improvement is needed

**Comment by regisb** [comment]
I was unable to reproduce this issue. Can you check whether the log file directories are properly mounted with `docker inspect ...`?

**Comment by e0d** [comment]
Yes, tracking logs don't work for me.  Can you specify what process you are
using for starting a session and whether you are seeing events in the
separate log file or in the combined log file.

**Comment by kdmccormick** [comment]
We have not been able to reproduce this.
