### ISSUE TITLE
Why does `tutor dev start` use the `--build` flag?

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#65]

**Comment by regisb** [comment]
because microfrontends :crying_cat_face:...

**Comment by kdmccormick** [comment]
of course 🤦🏻

**Comment by kdmccormick** [comment]
Closing this, as it's a subset of https://github.com/overhangio/2u-tutor-adoption/issues/87

**Comment by kdmccormick** [comment]
(fyi @rgraber)
