### ISSUE TITLE
Prototype persistent mounting interface as plugin(s)

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#66]
Using the V1 plugin API, try to implement something like this: https://github.com/overhangio/2u-tutor-adoption/issues/71. Experiment with using the plugin and see whether it feels like a better user experience than the plain `--mount` system.

**Comment by kdmccormick** [comment]
@connorhaugh, I think you mentioned you were going to work on this? If so, can I assign you to it?

**Comment by kdmccormick** [comment]
@connorhaugh can you comment on this so that I can add you as an assignee?

**Comment by connorhaugh** [comment]
Comment to be assigned

**Comment by kdmccormick** [comment]
@connorhaugh, Régis has started work upstream on a persistent mounting interface, so I don't think this plugin will be necessary any more.

Do you want me to help you find another DevX ticket to work on?
