### ISSUE TITLE
As a developer I want all code updates to be automatically reloaded

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#8]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

There are a few cases like discovery where changes are required to allow hot reloading of code

Note: there is a standard way of reloading code changes. We need to figure out a way to make it more convenient to load custom code in the development environment.

**Comment by regisb** [comment]
I'm not sure if there is anything else to be done here. To achieve that, plugin developers should implement the ["local-docker-compose-dev-services"](https://github.com/overhangio/tutor/blob/master/tutor/templates/dev/docker-compose.yml) to make sure that their Django services runs with `./manage.py runserver`. This is already the case with edx-platform and [ecommerce](https://github.com/overhangio/tutor-ecommerce/blob/master/tutorecommerce/patches/local-docker-compose-dev-services). Maybe that we should make this fact clearer by doing a better job at documenting patches (see #5).

**Comment by kdmccormick** [comment]
I haven't experienced any issues with this in my Tutor use so far 👍🏻 We'll make sure via patch docs that it's clear to plugin devs how to make their services automatically reload code.
