### ISSUE TITLE
Make ARM64 plugin official, with upstream images

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#81]
## Context

In https://github.com/overhangio/2u-tutor-adoption/issues/35, we resolved many of the blockers to running Tutor on ARM64. Thanks to @bradenmacdonald, there is a now a plugin that can be easily installed to enable ARM64 support: https://github.com/open-craft/tutor-contrib-arm64

This is great progress, but it's not sufficient for "ARM64 works out-of-the-box". See https://github.com/overhangio/tutor/pull/650 for more discussion on this topic.

## Acceptance Criteria

Roll ARM64 support into the base Tutor installation. One way to do this would be by making tutor-contrib-arm64 an official pre-installed plugin (which could be enabled as needed, perhaps even automatically). In this case, the plugin would need a dedicated maintainer.

If we want there to be hosted upstream ARM64 images for Tutor, then we need a sustainable way to host those and keep them up to date.

**Comment by bradenmacdonald** [comment]
BTW I recently updated the ARM images for the plugin so they should have a Nutmeg build as well as recent master working well.

**Comment by bradenmacdonald** [comment]
See discussion at https://github.com/open-craft/tutor-contrib-arm64/issues/1 and https://github.com/open-craft/tutor-contrib-arm64/pull/3

My perspective is that once Tutor is using MySQL 8 by default, the plugin will only be useful for providing default images. If @regisb is interested in using the code from https://github.com/open-craft/tutor-contrib-arm64/pull/3 to do automated multi-arch builds by default (which I think is de-risked now that I have it working), then there is no need for the plugin at all. But if he doesn't want to maintain those, then we'll need to keep the plugin going to allow people to switch to the unofficial images.

**Comment by regisb** [comment]
I agree that we should integrate this plugin in Tutor core such that arm64 users don't have to perform any extra steps. I'm grateful for Braden's suggestion to integrate the plugin code into Tutor core, so I suggest that we do exactly that starting from Palm. Thanks a lot!

**Comment by kdmccormick** [comment]
notes from devx meeting:

ARM64 plugin will be obviated by Palm.

to do: come back and check that we are all set here

are there more images to build?

**Comment by regisb** [comment]
> are there more images to build?

Oh yes! Basically, all images for all plugins. So far, there are a few which I have not managed to build. Here is the list: https://github.com/search?q=org%3Aoverhangio+IMAGES_BUILD_PLATFORM&type=code
(this is the CI option that configures image building for amd64 only)

**Comment by kdmccormick** [comment]
The remaining plugins without ARM64 images are:

* cairn -- not needed for devstack parity
* android -- not needed for devstack parity. Also, it seems that [this app will deprecated after Redwood.](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0064-arch-mobile-application-codebase-modernization.html)
* forum -- Needed for devstack parity

I'm going to close this since the big lift has already been done (thanks Braden and Régis!), and I'll track https://github.com/overhangio/tutor-forum/issues/23 as a follow-up for the forums.
