### ISSUE TITLE
As a deployer I want a clear upgrade path, ideally without downtime

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-developer-experience#9]
Copied in from [the existing backlog](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0). Needs grooming.

_________________________________

Note: this is a hard problem in the general case. Tutor already handles upgrades from one release to the next, but not for the master branch. Some R&D would be required.

**Comment by regisb** [comment]
The upgrade process was recently improved and better documented: https://docs.tutor.overhang.io/install.html#upgrading
I don't think there is anything left to do here.
