### ISSUE TITLE
fix: pass pytest common TestUserPostSaveCallback

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/wg-developer-experience#94]
As part of #36, several tests have been discovered that are not passing in tutor, but passing in devstack. The following tests may not be run by tutor, or may be failing in tutor.

common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::
- [x] test_paid_user_not_downgraded_on_activation_1_paid_bootcamp
- [x] test_paid_user_not_downgraded_on_activation_2_masters
- [x] test_paid_user_not_downgraded_on_activation_3_paid_executive_education
- [x] test_paid_user_not_downgraded_on_activation_4_professional
- [x] test_paid_user_not_downgraded_on_activation_5_verified
- [x] test_paid_user_not_downgraded_on_activation_7_no_id_professional
- [x] test_paid_user_not_downgraded_on_activation_8_credit

For more information about the tests that passed, failed, skipped, or never ran, see the [spreadsheet with all the tests](https://docs.google.com/spreadsheets/d/1CHiFOh2RpPlljNNF5rltEgOLGpKe1W35oy5Qms0-JXo/edit?usp=sharing).

**Comment by Carlos-Muniz** [comment]
All tests pass on tutor
```
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_not_enrolled_student_is_enrolled PASSED [  9%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__verified PASSED [ 18%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__masters PASSED [ 27%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__credit PASSED [ 36%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_is_marketable_set_to_false_for_user_created_via_management_command PASSED [ 45%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__no_id_professional PASSED [ 54%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_verified_student_not_downgraded_when_changing_email PASSED [ 63%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__executive_education PASSED [ 72%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__professional PASSED [ 81%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__paid_bootcamp PASSED [ 90%]
common/djangoapps/student/tests/test_models.py::TestUserPostSaveCallback::test_paid_user_not_downgraded_on_activation__paid_executive_education PASSED [100%]
```

**Comment by regisb** [comment]
SERIOUSLY?! This is freaking cool! huge achievement, congrats!

**Comment by Carlos-Muniz** [comment]
This test does pass in tutor. See https://github.com/openedx/wg-developer-experience/issues/155 for more details.
